baseURL = 'https://wangbm.github.io/bmio/'
languageCode = 'zh-cn'
title = 'bmio'
theme = 'shibui'

[params]
  author = "bmio"
  email = "hiwangbingmo@gmail.com"

[markup]
  [markup.tableOfContents]
    startLevel = 7  # Set to a high level to effectively disable TOC
    endLevel = 7

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
